name: React Native Checkbox CI
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Jest
        run: yarn test:jest
      - name: Type check
        run: yarn test:type-check
      - name: ESLint
        run: yarn test:eslint
